export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'
export const FACEBOOK_LOGIN_SUCCESS = 'facebook_login_success';
export const FACEBOOK_LOGIN_FAIL = 'facebook_login_fail';
export const AUTH_LOADING_ON = 'auth_loading_on'
export const AUTH_LOADING_OFF = 'auth_loading_off'
export const REGISTER_ADMIN_LOADING_ON = 'register_admin_loading_on'
export const REGISTER_ADMIN_LOADING_OFF = 'register_admin_loading_off'
export const REGISTER_CLIENT_LOADING_ON = 'register_client_loading_on'
export const REGISTER_CLIENT_LOADING_OFF = 'register_client_loading_off'
export const CLEAR_FORM = 'clear_form'
export const LOAD_LOGGEDIN_USER = 'load_loggedin_user'
export const EMAIL_PASSWORD_INPUT_FOCUS = 'email_password_input_focus'
export const USER_LOG_OUT_SUCCESS = 'user_log_out_success'
export const ADD_AREA_TO_ADMIN = 'add_area_to_admin'
export const REMOVE_AREA_TO_ADMIN = 'remove_area_to_admin'
export const REDIRECT_EXISTING_USER = 'redirect_existing_user'
export const REGISTERING_ON = 'registering_on'
export const REGISTERING_OFF = 'registering_off'
export const LOAD_REDIRECTED_USER = 'load_redirected_user'
export const LOAD_AVAILABLE_USER = 'load_available_user'
export const USER_LOADED_TRUE = 'user_loaded_true'
export const USER_LOADED_FALSE = 'user_loaded_false'
export const LOAD_AVATAR = 'load_avatar'


export const FACEBOOK_LOGOUT_SUCCESS = 'facebook_logout_success'
export const RESET_APPLICATION_TO_INITIAL_STATE = 'reset_application_to_initial_state'

export const NAME_ADMIN_REGISTER_CHANGED = 'name_admin_register_changed'
export const EMAIL_ADMIN_REGISTER_CHANGED = 'email_admin_register_changed'
export const COMPANY_NAME_ADMIN_REGISTER_CHANGED = 'company_name_admin_register_changed'
export const PHONE_ADMIN_REGISTER_CHANGED = 'phone_admin_register_changed'
export const PASSWORD_ADMIN_REGISTER_CHANGED = 'password_admin_register_changed'
export const PASSWORD_CONFIRMATION_ADMIN_REGISTER_CHANGED = 'password_confirmation_admin_register_changed'

export const STREET_NAME_ADMIN_REGISTER_CHANGED = 'street_name_admin_register_changed'
export const NUMBER_ADMIN_REGISTER_CHANGED = 'number_admin_register_changed'
export const CITY_ADMIN_REGISTER_CHANGED = 'city_admin_register_changed'
export const STATE_ADMIN_REGISTER_CHANGED = 'state_admin_register_changed'
export const CEP_ADMIN_REGISTER_CHANGED = 'cep_admin_register_changed'
export const SERVICE_AT_HOME_ADMIN_REGISTER_CHANGED = 'service_at_home_admin_register_changed'
export const ADDITIONAL_INFO_ADMIN_REGISTER_CHANGED = 'additional_info_home_admin_register_changed'
export const LOAD_STATES = 'load_states'
export const LOAD_CITIES = 'load_cities'
export const CLEAR_CITY = 'clear_city'
export const SET_PIC_TO_NULL = 'set_pic_to_null'


export const ADMIN_USER_REGISTERED_SUCCESS = 'admin_user_registered_success'
export const ADMIN_USER_REGISTERED_FAILED = 'admin_user_registered_failed'
export const CONTINUE_ADMIN_REGISTRATION = 'continue_admin_registration'
export const SELECT_MONDAY = 'select_monday'
export const SELECT_TUESDAY = 'select_tuesday'
export const SELECT_WEDNESDAY = 'select_wednesday'
export const SELECT_THURSDAY = 'select_thursday'
export const SELECT_FRIDAY = 'select_friday'
export const SELECT_SATURDAY = 'select_saturday'
export const SELECT_SUNDAY = 'select_sunday'
export const UNSELECT_MONDAY = 'unselect_monday'
export const UNSELECT_TUESDAY = 'unselect_tuesday'
export const UNSELECT_WEDNESDAY = 'unselect_wednesday'
export const UNSELECT_THURSDAY = 'unselect_thursday'
export const UNSELECT_FRIDAY = 'unselect_friday'
export const UNSELECT_SATURDAY = 'unselect_saturday'
export const UNSELECT_SUNDAY = 'unselect_sunday'
export const SET_SATURDAY_HOUR_START = 'set_saturday_hour_start'
export const SET_SATURDAY_HOUR_END = 'set_saturday_hour_end'
export const SET_SUNDAY_HOUR_START = 'set_sunday_hour_start'
export const SET_SUNDAY_HOUR_END = 'set_sunday_hour_end'
export const CHECK_IF_USER_EXISTS_BY_EMAIL = 'check_if_user_exists_by_email'


export const ADD_NEW_SERVICE = 'add_new_service'
export const NEW_SERVICE_NAME_CHANGED = 'new_service_name_changed'
export const NEW_SERVICE_DURATION_TIME_CHANGED = 'new_service_duration_time_changed'
export const NEW_SERVICE_DESCRIPTION_CHANGED = 'new_service_description_changed'
export const NEW_SERVICE_PRICE_CHANGED = 'new_service_price_changed'
export const NEW_SERVICE_EMPLOYEE_SELECT = 'new_service_employee_select'
export const COMPANY_HOURS_START = 'company_hours_start'
export const COMPANY_HOURS_END = 'company_hours_end'
export const NEW_SERVICE_ADDED_SUCCESS = 'new_service_added_success'

export const NAME_CLIENT_REGISTER_CHANGED = 'name_client_register_changed'
export const EMAIL_CLIENT_REGISTER_CHANGED = 'email_client_register_changed'
export const PHONE_CLIENT_REGISTER_CHANGED = 'phone_client_register_changed'
export const PASSWORD_CLIENT_REGISTER_CHANGED = 'password_client_register_changed'
export const PASSWORD_CONFIRMATION_CLIENT_REGISTER_CHANGED = 'password_confirmation_client_register_changed'
export const CLIENT_USER_REGISTERED_SUCCESS = 'client_user_registered_success'
export const CONTINUE_CLIENT_REGISTRATION = 'continue_client_registration'


//MAIN ADMIN SCREEN
export const LOAD_ADMIN_USER_INFO = 'load_admin_user_info'


//EMPLOYEES
export const SHOW_CURRENT_EMPLOYEES = 'show_current_employees'
export const NEW_EMPLOYEE_NAME_CHANGED = 'new_employee_name_changed'
export const NEW_EMPLOYEE_PHOTO_CHANGED = 'new_employee_photo_changed'
export const NEW_EMPLOYEE_LOADING_ON = 'new_employee_loading_on'
export const NEW_EMPLOYEE_LOADING_OFF = 'new_employee_loading_off'
export const NEW_EMPLOYEE_ADDED = 'new_employee_added'
export const CLEAR_EMPLOYEE_FORM = 'clear_employee_form'
export const EDIT_EMPLOYEE_SUCCESS = 'edit_employee_success'
export const NEW_EMPLOYEE_ID_CHANGED = 'new_employee_id_changed'
export const EMPLOYEE_ADDED_TO_SELECTION = 'employee_added_to_selection'
export const EMPLOYEE_REMOVED_FROM_SELECTION = 'employee_removed_from_selection'
export const SELECTED_EMPLOYEE_ID = 'selected_employee_id'


//REGISTERED SERVICES SCREEN
export const LOAD_REGISTERED_SERVICES = 'load_registered_services'
export const FIND_EMPLOYEES_NAMES_BY_ID = 'find_employees_names_by_id'
export const CLEAR_SERVICE_FORM = 'clear_service_form'
export const START_EDIT_SERVICE = 'start_edit_service'
export const EDIT_SERVICE = 'edit_service'
export const EDIT_SERVICE_SUCCESS = 'edit_service_success'
export const SERVICE_LOADING = 'service_loading'
export const SET_SERVICE_MODE = ''


// SERVICES CLIENT
export const LOAD_AVAILABLE_SERVICES = 'load_available_services'
export const LOADING_CLIENT_SERVICES_ON = 'loading_client_services_on'
export const LOADING_CLIENT_SERVICES_OFF = 'loading_client_services_off'
export const LOAD_AVAILABLE_BUSINESSES = 'load_available_businesses'
export const ADD_BUSINESS_TO_MAIN_LIST = 'add_business_to_main_list'
export const CLEAR_MAIN_BUSINESS_LIST = 'clear_main_business_list'