export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'
export const FACEBOOK_LOGIN_SUCCESS = 'facebook_login_success';
export const FACEBOOK_LOGIN_FAIL = 'facebook_login_fail';
export const AUTH_LOADING_ON = 'auth_loading_on'
export const AUTH_LOADING_OFF = 'auth_loading_off'
export const REGISTER_ADMIN_LOADING_ON = 'register_admin_loading_on'
export const REGISTER_ADMIN_LOADING_OFF = 'register_admin_loading_off'
export const REGISTER_CLIENT_LOADING_ON = 'register_client_loading_on'
export const REGISTER_CLIENT_LOADING_OFF = 'register_client_loading_off'
export const CLEAR_FORM = 'clear_form'
export const LOAD_LOGGEDIN_USER = 'load_loggedin_user'

export const FACEBOOK_LOGOUT_SUCCESS = 'facebook_logout_success'

export const NAME_ADMIN_REGISTER_CHANGED = 'name_admin_register_changed'
export const EMAIL_ADMIN_REGISTER_CHANGED = 'email_admin_register_changed'
export const COMPANY_NAME_ADMIN_REGISTER_CHANGED = 'company_name_admin_register_changed'
export const PHONE_ADMIN_REGISTER_CHANGED = 'phone_admin_register_changed'
export const PASSWORD_ADMIN_REGISTER_CHANGED = 'password_admin_register_changed'
export const PASSWORD_CONFIRMATION_ADMIN_REGISTER_CHANGED = 'password_confirmation_admin_register_changed'
export const ADMIN_USER_REGISTERED_SUCCESS = 'admin_user_registered_success'
export const ADMIN_USER_REGISTERED_FAILED = 'admin_user_registered_failed'
export const CONTINUE_ADMIN_REGISTRATION = 'continue_admin_registration'
export const SELECT_MONDAY = 'select_monday'
export const SELECT_TUESDAY = 'select_tuesday'
export const SELECT_WEDNESDAY = 'select_wednesday'
export const SELECT_THURSDAY = 'select_thursday'
export const SELECT_FRIDAY = 'select_friday'
export const SELECT_SATURDAY = 'select_saturday'
export const SELECT_SUNDAY = 'select_sunday'
export const UNSELECT_MONDAY = 'unselect_monday'
export const UNSELECT_TUESDAY = 'unselect_tuesday'
export const UNSELECT_WEDNESDAY = 'unselect_wednesday'
export const UNSELECT_THURSDAY = 'unselect_thursday'
export const UNSELECT_FRIDAY = 'unselect_friday'
export const UNSELECT_SATURDAY = 'unselect_saturday'
export const UNSELECT_SUNDAY = 'unselect_sunday'
export const SET_SATURDAY_HOUR_START = 'set_saturday_hour_start'
export const SET_SATURDAY_HOUR_END = 'set_saturday_hour_end'
export const SET_SUNDAY_HOUR_START = 'set_sunday_hour_start'
export const SET_SUNDAY_HOUR_END = 'set_sunday_hour_end'
export const CHECK_IF_USER_EXISTS_BY_EMAIL = 'check_if_user_exists_by_email'

export const ADD_NEW_SERVICE = 'add_new_service'
export const NEW_SERVICE_NAME_CHANGED = 'new_service_name_changed'
export const NEW_SERVICE_DURATION_TIME_CHANGED = 'new_service_duration_time_changed'
export const NEW_SERVICE_DESCRIPTION_CHANGED = 'new_service_description_changed'
export const NEW_SERVICE_PRICE_CHANGED = 'new_service_price_changed'
export const NEW_SERVICE_EMPLOYEE_SELECT = 'new_service_employee_select'
export const COMPANY_HOURS_START = 'company_hours_start'
export const COMPANY_HOURS_END = 'company_hours_end'
export const NEW_SERVICE_ADDED_SUCCESS = 'new_service_added_success'

export const NAME_CLIENT_REGISTER_CHANGED = 'name_client_register_changed'
export const EMAIL_CLIENT_REGISTER_CHANGED = 'email_client_register_changed'
export const PHONE_CLIENT_REGISTER_CHANGED = 'phone_client_register_changed'
export const PASSWORD_CLIENT_REGISTER_CHANGED = 'password_client_register_changed'
export const PASSWORD_CONFIRMATION_CLIENT_REGISTER_CHANGED = 'password_confirmation_client_register_changed'
export const CLIENT_USER_REGISTERED_SUCCESS = 'client_user_registered_success'
export const CONTINUE_CLIENT_REGISTRATION = 'continue_client_registration'


//MAIN ADMIN SCREEN
export const LOAD_ADMIN_USER_INFO = 'load_admin_user_info'


//EMPLOYEES
export const SHOW_CURRENT_EMPLOYEES = 'show_current_employees'
export const NEW_EMPLOYEE_NAME_CHANGED = 'new_employee_name_changed'
export const NEW_EMPLOYEE_PHOTO_CHANGED = 'new_employee_photo_changed'
export const NEW_EMPLOYEE_LOADING_ON = 'new_employee_loading_on'
export const NEW_EMPLOYEE_LOADING_OFF = 'new_employee_loading_off'
export const NEW_EMPLOYEE_ADDED = 'new_employee_added'
export const CLEAR_EMPLOYEE_FORM = 'clear_employee_form'
export const EDIT_EMPLOYEE_SUCCESS = 'edit_employee_success'
export const NEW_EMPLOYEE_ID_CHANGED = 'new_employee_id_changed'
export const EMPLOYEE_ADDED_TO_SELECTION = 'employee_added_to_selection'
export const EMPLOYEE_REMOVED_FROM_SELECTION = 'employee_removed_from_selection'
export const SELECTED_EMPLOYEE_ID = 'selected_employee_id'


//REGISTERED SERVICES SCREEN
export const LOAD_REGISTERED_SERVICES = 'load_registered_services'
export const FIND_EMPLOYEES_NAMES_BY_ID = 'find_employees_names_by_id'
